name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}/GUITesting
  QT_VERSION:   5.15.2
  QMAKE_PATH: ${{ github.workspace }}/GUITesting/Qt/5.15.2/gcc_64/bin/qmake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update package
      run: sudo apt-get update
    - name: install lggpiod
      run: |
        sudo apt install python3
        wget https://github.com/joan2937/lg/archive/master.zip
        unzip master.zip
        cd lg-master
        make
        sudo make install
        ls /usr/local/lib
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version:      ${{ env.QT_VERSION }}
        host:         linux
        target:       desktop
        arch:         gcc_64
        dir:          ${{ env.SOURCE_DIR }}
        setup-python: false
    - name: echo variable
      run: echo $QMAKE_PATH
    - name: run build script
      run: |
        cd ${{ env.SOURCE_DIR }}
        sudo ./build.sh $QMAKE_PATH

