name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}/GUITesting
  QT_VERSION:   5.15.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update package
      run: sudo apt-get update
    - name: install lggpiod
      run: |
        sudo apt install python3
        wget https://github.com/joan2937/lg/archive/master.zip
        unzip master.zip
        cd lg-master
        make
        sudo make install
        ls /usr/local/lib
    - name: Install Qt
      run: |
        sudo apt-get install build-essential
        sudo apt-get install qtcreator
        sudo apt install qt5-default
        sudo apt-get build-dep qtmultimedia5-dev
        sudo apt-get install qtmultimedia5-dev
        sudo apt-get install libqt5multimedia5-plugins
    - name: where is qmake
      run: whereis qmake
    - name: run build script
      run: |
        cd ${{ env.SOURCE_DIR }}
        sudo whereis qmake | ./build.sh 

